-- This SQL script creates a table named 'states' if it does not already exist.
-- Create Schema terraform_backend.terraform_remote_state
-- The table has three columns: 'id', 'name', and 'data'.
-- The 'id' column is of type bigint, has a default value generated by the sequence 'global_states_id_seq',
-- and is the primary key of the table.
-- The 'name' column is of type text and must be unique.
-- The 'data' column is of type text.

CREATE SCHEMA terraform_remote_state;

CREATE TABLE IF NOT EXISTS terraform_remote_state.states
(
    id   BIGINT DEFAULT nextval('global_states_id_seq'::regclass) NOT NULL
        PRIMARY KEY,
    name TEXT
        UNIQUE,
    data TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS states_by_name
    ON terraform_remote_state.states (name);